---
- hosts: group5
  become: yes
  become_method: su
  become_user: root
  gather_facts: no

  tasks:
    - name: Creates directory /raiz
        file:
          path: /raiz
          state: directory

    - name: Change file ownership, group and permissions /raiz
      file:
        path: /raiz
        owner: root
        group: root
        mode: '0770'
...