---
- hosts: all
  var_files:
    - vars1.yml
  tasks:
    - name: install pkg + run packes + intial +1
      yum:
        name: "{{ db_pkg }}"
        state: latest
    - name: start {{ db_srv }}
      service:
        name: "{{ db_srv }}"
        state: started
        enabled: true
...